name: planet_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_rating_bar: ^4.0.1
  group_button: ^5.2.2
  hexcolor: ^3.0.1
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/